site_name: Fail2ban Dashboard - Documentación Técnica
site_description: Documentación completa del sistema de monitoreo Fail2ban
site_author: Alejandro Gómez
site_url: https://github.com/AleGC019/fail2ban-dashboard-docs-front.git

theme:
  name: material
  language: es
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
  - scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-7
      name: Cambiar a modo oscuro
  - scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-4
      name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

extra_css:
  - assets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

nav:
  - Inicio: index.md
  - Manual de Usuario:
    - Introducción: user-guide/introduction.md
    - Primeros Pasos: user-guide/getting-started.md
    - Autenticación: user-guide/authentication.md
    - Navegación: user-guide/navigation.md
    - Dashboard Principal: user-guide/dashboard.md
    - Gestión de Logs: user-guide/logs-management.md
    - IPs Bloqueadas: user-guide/banned-ips.md
    - Gestión de Usuarios: user-guide/user-management.md
    - Solución de Problemas: user-guide/troubleshooting.md
  - API Reference:
    - Referencia de la API: api/reference.md
    - Autenticación: api/authentication.md
  - Arquitectura del Sistema:
    - Descripción General: arquitectura/overview.md

plugins:
  - search:
      lang: es
  - git-revision-date-localized:
      fallback_to_build_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AleGC019/fail2ban-dashboard
    - icon: fontawesome/solid/globe
      link: https://alertasfail2ban.xmakuno.com